stages:
  - install
  - build
  - deploy

variables:
  APP_NAME: "stellar"
  PM2_APP_NAME: "stellar"
  DEPLOY_SERVER: "65.2.9.239"
  DEPLOY_USER: "root"
  DEPLOY_PATH: "/path/to/your/app"
  SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next/

deploy:
  stage: deploy
  script:
    - echo "Deploying to server..."
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "mkdir -p $DEPLOY_PATH"
    - rsync -av --delete-after --exclude=node_modules --exclude=.git . $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
    - ssh $DEPLOY_USER@$DEPLOY_SERVER "
        cd $DEPLOY_PATH &&
        npm install --production &&
        npm run build &&
        pm2 restart $PM2_APP_NAME || pm2 start npm --name '$PM2_APP_NAME' -- start
      "
  only:
    - main